[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "dist/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
